services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: globalmitra-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Subash@@2314##21"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Subash@@2314##21' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s

  backend:
    build: .
    container_name: globalmitra-backend
    ports:
      - "8005:8000"
    environment:
      DEBUG: "True"
      DB_NAME: "GlobalMitraDB"
      DB_USER: "sa"
      DB_PASSWORD: "Subash@@2314##21"
      DB_HOST: "db"
      DB_PORT: "1433"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "admin123"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  adminer:
    image: adminer:latest
    container_name: globalmitra-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  sqlserver_data: